/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BondsRouteImport } from './routes/bonds'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as CastIdRouteImport } from './routes/cast.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BondsRoute = BondsRouteImport.update({
  id: '/bonds',
  path: '/bonds',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const CastIdRoute = CastIdRouteImport.update({
  id: '/cast/$id',
  path: '/cast/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bonds': typeof BondsRoute
  '/studio': typeof StudioRoute
  '/cast/$id': typeof CastIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bonds': typeof BondsRoute
  '/studio': typeof StudioRoute
  '/cast/$id': typeof CastIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bonds': typeof BondsRoute
  '/studio': typeof StudioRoute
  '/cast/$id': typeof CastIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/bonds' | '/studio' | '/cast/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/bonds' | '/studio' | '/cast/$id'
  id: '__root__' | '/' | '/bonds' | '/studio' | '/cast/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BondsRoute: typeof BondsRoute
  StudioRoute: typeof StudioRoute
  CastIdRoute: typeof CastIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bonds': {
      id: '/bonds'
      path: '/bonds'
      fullPath: '/bonds'
      preLoaderRoute: typeof BondsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cast/$id': {
      id: '/cast/$id'
      path: '/cast/$id'
      fullPath: '/cast/$id'
      preLoaderRoute: typeof CastIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BondsRoute: BondsRoute,
  StudioRoute: StudioRoute,
  CastIdRoute: CastIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
